-- Q1. Total orders
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM orders;

-- Q2. Total delivered orders
SELECT COUNT(DISTINCT order_id) AS delivered_orders
FROM orders
WHERE order_status = 'delivered';

-- Q3. Total customers
SELECT COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers;

-- Q4. Total Sellers
SELECT COUNT(DISTINCT seller_id) AS total_sellers
FROM sellers;

-- Q5. Cancellation rate
SELECT
    ROUND(
        100.0 * SUM(order_status = 'canceled')
        / COUNT(*),
        2
    ) AS cancellation_rate
FROM orders;

-- Q6. Revenue
SELECT
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered';

-- Q7. Average Order Value
SELECT
    ROUND(
        SUM(oi.price) / COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered';

-- Q8. Average Basket Size
-- Average number of products/items per completed order.
SELECT
    ROUND(
        COUNT(*) / COUNT(DISTINCT o.order_id),
        2
    ) AS average_basket_size
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered';

-- Q9. Monthly Revenue
SELECT
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    ROUND(SUM(oi.price), 2) AS revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
ORDER BY month;

-- Q10. Monthly Orders
SELECT
    DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS month,
    COUNT(*) AS orders
FROM orders
GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m')
ORDER BY month;

-- Q11. Top Product Categories
SELECT
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;

-- Q12. Payment Methods
SELECT
    payment_type,
    COUNT(*) AS payment_count,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM order_payments
GROUP BY payment_type
ORDER BY payment_count DESC;

-- Q13. Average Delivery Time
SELECT
    ROUND(AVG(delivery_days), 2) AS average_delivery_days
FROM orders
WHERE order_status = 'delivered'
AND delivery_days IS NOT NULL;

-- Q14. Review Score
SELECT
    ROUND(AVG(review_score), 2) AS average_review_score
FROM order_reviews;

-- Q15. Review distribution
SELECT
    review_score,
    COUNT(*) AS review_count
FROM order_reviews
GROUP BY review_score
ORDER BY review_score;

-- Q16. Top Sellers
SELECT
    oi.seller_id,
    ROUND(SUM(oi.price), 2) AS revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY oi.seller_id
ORDER BY revenue DESC
LIMIT 10;

-- Q17. Revenue by Seller State
SELECT
    s.seller_state,
    ROUND(SUM(oi.price), 2) AS revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
JOIN sellers s
    ON oi.seller_id = s.seller_id
WHERE o.order_status = 'delivered'
GROUP BY s.seller_state
ORDER BY revenue DESC;

-- Q18. Repeat Customers
SELECT
    COUNT(*) AS repeat_customers
FROM (
    SELECT
        c.customer_unique_id
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'delivered'
    GROUP BY c.customer_unique_id
    HAVING COUNT(DISTINCT o.order_id) > 1
) AS repeat_customer_table;

-- Q19. Average Orders per Customer
SELECT 
    ROUND(COUNT(DISTINCT o.order_id) / COUNT(DISTINCT c.customer_unique_id),
            2) AS avg_orders_per_customer
FROM
    customers c
        JOIN
    orders o ON c.customer_id = o.customer_id
WHERE
    o.order_status = 'delivered';

-- Q20. Historical Customer Value
-- Historical customer value = total completed-order revenue generated by a customer.
SELECT
    c.customer_unique_id,
    ROUND(SUM(oi.price), 2) AS customer_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_unique_id
ORDER BY customer_value DESC
LIMIT 20;

-- Rank sellers by revenue
WITH seller_revenue AS (
    SELECT
        oi.seller_id,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
)

SELECT
    seller_id,
    ROUND(revenue, 2) AS revenue,
    RANK() OVER (ORDER BY revenue DESC) AS seller_rank
FROM seller_revenue
ORDER BY seller_rank
LIMIT 10;

-- Monthly revenue + previous month
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
        SUM(oi.price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY month
)

SELECT
    month,
    ROUND(revenue, 2) AS revenue,
    ROUND(
        LAG(revenue) OVER (ORDER BY month),
        2
    ) AS previous_month_revenue
FROM monthly_revenue
ORDER BY month;

-- Revenue contribution by category
WITH category_revenue AS (
    SELECT
        p.product_category_name AS category,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.order_status = 'delivered'
    GROUP BY p.product_category_name
)

SELECT
    category,
    ROUND(revenue, 2) AS revenue,
    ROUND(
        100 * revenue / SUM(revenue) OVER (),
        2
    ) AS revenue_percentage
FROM category_revenue
ORDER BY revenue DESC;
